#!/bin/bash

APPSTORE_STATE=${1:-$APPSTORE_STATE}         # Set to ARG1 if ARG1
if [[ ! -f ${APPSTORE_STATE:=$HOME/.appstore.state} ]]; then
    echo Homebrew Statefile: $APPSTORE_STATE does not exist.
    echo
    echo USAGE: brew restore [appstore.state]
    echo
    echo If statefile is omitted, \'$APPSTORE_STATE\' will be used by default.
    echo You can change this by setting APPSTORE_STATE
    echo
    exit
fi

cut -sd ' ' -f 1 < $APPSTORE_STATE | xargs -n1 mas install
