#!/bin/bash

HOMEBREW_CASK_STATE=${1:-$HOMEBREW_CASK_STATE}         # Set to ARG1 if ARG1
if [[ ! -f ${HOMEBREW_CASK_STATE:=$HOME/.homebrew.cask.state} ]]; then
    echo Homebrew Statefile: $HOMEBREW_CASK_STATE does not exist.
    echo
    echo USAGE: brew restore [homebrew.cask.state]
    echo
    echo If statefile is omitted, \'$HOMEBREW_CASK_STATE\' will be used by default.
    echo You can change this by setting HOMEBREW_CASK_STATE
    echo
    exit
fi

while read PACKAGE; do
    [[ ! -z $PACKAGE ]] && brew cask install $PACKAGE
done <"$HOMEBREW_CASK_STATE"
